services:
  db:
    image: ${POSTGRES_IMAGE:-postgres:latest}
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres_db_tonton}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-anhquan}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-anhquandeptrai}
      POSTGRES_DB: ${POSTGRES_DB:-tonton}
    ports:
      - "${POSTGRES_PORT:-5434}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
